# Generated by Django 6.1.1 on 2026-09-15 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_voiture', models.CharField(help_text='Ex: Corolla, 208', max_length=50, verbose_name='Modèle du véhicule')),
                ('marque_voiture', models.CharField(help_text='Ex: Toyota, Peugeot', max_length=50, verbose_name='Marque du véhicule')),
                ('plaque', models.CharField(max_length=20, unique=True, verbose_name="Plaque d'immatriculation")),
                ('nombres_de_places', models.PositiveIntegerField(default=4, verbose_name='Nombre de places disponibles')),
                ('couleur', models.CharField(blank=True, max_length=30, null=True, verbose_name='Couleur')),
                ('est_climatisee', models.BooleanField(default=False, verbose_name='Véhicule climatisé')),
                ('photo_voiture', models.ImageField(blank=True, null=True, upload_to='voitures/', verbose_name='Photo de la voiture')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_Maj', models.DateTimeField(auto_now=True)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voitures', to=settings.AUTH_USER_MODEL, verbose_name='Conducteur')),
            ],
            options={
                'verbose_name': 'Voiture',
                'verbose_name_plural': 'Voitures',
                'ordering': ['-date_creation'],
            },
        ),
    ]
