# Generated by Django 6.1.1 on 2026-09-15 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voitures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu_depart', models.CharField(max_length=255, verbose_name='Lieu de départ')),
                ('destination', models.CharField(max_length=255, verbose_name="Lieu d'arrivée")),
                ('date', models.DateField(verbose_name='Date de départ')),
                ('heure_depart', models.TimeField(verbose_name='Heure de départ')),
                ('places_disponibles', models.PositiveIntegerField(verbose_name='Places disponibles')),
                ('prix_par_place', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix par place (FCFA)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Note aux passagers')),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PLANIFIE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets_publies', to=settings.AUTH_USER_MODEL, verbose_name='Conducteur')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to='voitures.voiture', verbose_name='Voiture utilisée')),
            ],
            options={
                'verbose_name': 'Trajet',
                'verbose_name_plural': 'Trajets',
                'ordering': ['date'],
            },
        ),
    ]
