# Generated by Django 6.1 on 2026-09-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='preferences',
            field=models.JSONField(blank=True, default=list, verbose_name='Préférences du trajet'),
        ),
    ]
