# Generated by Django 6.1.1 on 2026-09-29 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trajets', '0002_trajet_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_applique', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée')], default='en_attente', max_length=20)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('methode_paiement', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_transaction', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL)),
                ('trajet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='trajets.trajet')),
            ],
        ),
    ]
