# Generated by Django 6.1.1 on 2026-09-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assurance',
            field=models.FileField(blank=True, null=True, upload_to='documents/cg/'),
        ),
        migrations.AddField(
            model_name='user',
            name='carte_grise',
            field=models.FileField(blank=True, null=True, upload_to='documents/cni/'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='permis_conduire',
            field=models.FileField(blank=True, null=True, upload_to='documents/permis/'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profil/'),
        ),
    ]
