# Generated by Django 6.1.1 on 2026-09-15 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_assurance_user_carte_grise_user_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assurance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='carte_grise',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permis_conduire',
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permis_conduire', models.FileField(upload_to='documents/permis/')),
                ('carte_grise', models.FileField(upload_to='documents/carte_grise/')),
                ('assurance', models.FileField(upload_to='documents/assurance/')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=10)),
                ('motif_rejet', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
