# Generated by Django 6.1.1 on 2026-09-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_assurance_remove_user_carte_grise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationdocument',
            name='photo_vehicule',
            field=models.ImageField(blank=True, help_text='Photo du véhicule pour la vérification initiale de son état.', null=True, upload_to='verification_vehicles/'),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='motif_rejet',
            field=models.TextField(blank=True, help_text="Motif expliquant le rejet du dossier (rempli par l'administrateur).", null=True),
        ),
    ]
