# Generated by Django 6.1.1 on 2026-10-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_codeverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeverification',
            name='type_code',
            field=models.CharField(choices=[('ACTIVATION', 'Activation de compte'), ('RESET_PASSWORD', 'Réinitialisation de mot de passe')], default='ACTIVATION', max_length=20, verbose_name='Type de vérification'),
        ),
    ]
