# Generated by Django 6.1.1 on 2026-10-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_codeverification_type_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Numéro de téléphone'),
        ),
    ]
